<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RazorTemplate.Common/RazorTemplate.Common.csproj" />
    <ProjectReference Include="../RazorTemplate.Components/RazorTemplate.Components.csproj" />
  </ItemGroup>

</Project>
